### ISSUE TITLE
Arc<Mutex> vs RxTx

### ISSUE THREAD

**Issue by soundprojects** [soundprojects/trainsim#2]
What are the pro's and cons of using Arc<Mutex> vs using channels for state sharing among async tasks?

**Comment by ruurdadema** [comment]
On higher level, an Arc<Mutex<>> wrapping some data structure represents state, where a channel represents an event (update, request, notification). The advantage of Arc<Mutex<>> is that it produces less boilerplate code, and is kind of 'straightforward'. 
On the other hand, channels need to be split into Rx & Tx objects which need to be passed around. If a channel should support multiple types of messages then a wrapper enum has to be created, and there has to be done some switching on that to find out what inner type the enum contains.
Sometimes it can be hard to correctly pass around the Arc<Mutex<>> and void global state.

**Comment by ruurdadema** [comment]
I think this [example](https://github.com/tokio-rs/tokio/blob/master/examples/tinydb.rs) from Tokio might be very useful for you.
